version: '3'
services:
  yuno:
    build:
      dockerfile: docker/Dockerfile
      context: .
    volumes:
    - ./:/var/www/html/yuno
    working_dir: /var/www/html/yuno
    container_name: yuno
    tty: true